### ISSUE TITLE
[cloudcost-exporter]: Road to open source

### ISSUE THREAD

**Issue by Pokom** [grafana/cloudcost-exporter#5]
We reached consesnus in the [cloudcost-exporter](https://docs.google.com/document/d/1Xf2HDosUuzyPQ-v8tcsl7HR71wh7ic5y1BhMgXD0nf8/edit) design document that we will work towards open sourcing the project _with_ a compute module. This issue is meant to track the work necessary to see it through and communicate progress.

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/cloudcost-exporter/issues/1
- [ ] https://github.com/grafana/cloudcost-exporter/issues/2
- [ ] https://github.com/grafana/cloudcost-exporter/issues/3
- [ ] https://github.com/grafana/deployment_tools/issues/96164
- [ ] https://github.com/grafana/cloudcost-exporter/issues/56
- [ ] https://github.com/grafana/cloudcost-exporter/issues/33
- [ ] https://github.com/grafana/cloudcost-exporter/issues/80
- [ ] https://github.com/grafana/deployment_tools/issues/117678
- [ ] https://github.com/grafana/cloudcost-exporter/issues/4
- [ ] https://github.com/grafana/cloudcost-exporter/issues/21
- [ ] https://github.com/grafana/cloudcost-exporter/issues/19
```

**Comment by Pokom** [comment]
Completed as of Friday, May 2nd 🎉
