### ISSUE TITLE
Persistent Volume Hourly Cost Metric

### ISSUE THREAD

**Issue by Pokom** [grafana/cloudcost-exporter#95]
So far we've focused our efforts on exporting metrics for the following resources:
- compute
- blob storage

One metric distinctly missing is tracking the hourly cost for persistent volumes. 
We would need two metrics:
- Hourly Cost of Storage for the persistent volume (rate)
- Amount(in GiB) allocated by the Persistent Volume Claim (usage)

These two metrics can then be joined together to calculate the total in spend (`spend = usage * rate`) for persistent volumes. 

For both metrics, we need need the following labels:
- `persistentvolume` - The name of the persistent volume
- `namespace` - The namespace the pvc exists in
- `cluster` - The cluster the pvc exists in
- `storage_class` - Whether or not it's an SSD or HDD
- `location` - The region the pvc lives in

```[tasklist]
### Tasks
- [x] Implement persistent volume in GCP
- [ ] https://github.com/grafana/cloudcost-exporter/issues/235
- [ ] https://github.com/grafana/cloudcost-exporter/issues/236
```

**Comment by Pokom** [comment]
Closing in favor of using existing issues. AWS is being implemented by @paulajulve(https://github.com/grafana/deployment_tools/issues/149203), and Azure still has to be planned out and picked up.

**Comment by Pokom** [comment]
This is a test
